### ISSUE TITLE
Missing images in Almodovar documentation

### ISSUE THREAD

**Issue by placido** [bebanjo/almodovar#31]
Some images are missing from the Almodovar documentation. For instance, see at: https://github.com/bebanjo/almodovar/wiki/Movida-API 

The following paragraph:
![image](https://cloud.githubusercontent.com/assets/1046884/12116861/b976df5a-b3b4-11e5-8ef6-e35888aaee41.png)
is missing the following image:
![image](https://cloud.githubusercontent.com/assets/1046884/12116870/c6e52d72-b3b4-11e5-8cb8-2731af02f922.png)

This is just one example, the issue may be elsewhere too.

It is possible that the issue relates to Content Security Policies:
![image](https://cloud.githubusercontent.com/assets/1046884/12116912/fb29e6ea-b3b4-11e5-91a4-2e6529028c86.png)

**Comment by miguelff** [comment]
Fixed in wiki repository
