### ISSUE TITLE
Display validation errors to the user

### ISSUE THREAD

**Issue by cavalle** [bebanjo/almodovar#4]
Currently, POSTing and PUTing to an Almodovar server can return a 422 response including a list of errors. Almodovar client should understand this response and give the user a way to access the list of errors

**Comment by pacoguzman** [comment]
I think the current implementation is not totally wrong but can be improved of course. For example:

```ruby
begin
  collection_resource.collection_entries.create(collection_entry: {title: title_resource}) 
rescue Almodovar::HttpError => exception
  unless exception.response_code == 422 && exception.response_body =~ /Title has already been 
taken/
    raise exception
  end
end
```

I that way we can check the current error response that came from the Bebanjo APIs

**Comment by demimismo** [comment]
Adding this to our internal list of technical tasks, we really need this for our components.

**Comment by pacoguzman** [comment]
After talk with @demimismo when as there wasn't any task on the board, I can start this next & technical-task issue

**Comment by pacoguzman** [comment]
@demimismo I'm returning back to the pool, I would like to talk about this because at first sight this is compicated to insert in the Almodovar magic world

**Comment by pacoguzman** [comment]
This is my proposal for create/update/delete requests to have something like this:

```ruby
begin
  collection_resource.create(resource: attributes) 
rescue Almodovar::ValidationErrors => exception
  exception.error_messages # => ['Title has already been taken']
end
```

The thing is that can be very disruptive that we change what we return from this methods, because other option can be

```ruby
begin
  resource_response = collection_resource.create(resource: attributes) 
  if resource_response.errors?
    resource_response.response_body # => full response body from the server
    resource_response.response_status # => 422 that's the only one we can start rescuing
    resource_response.error_messages # =>['Title has already been taken']
  else
     resource_response.resource # => which return what we're currently returning when everything is fine
  end
rescue Almodovar::HttpError
end
```

**Comment by demimismo** [comment]
@pacoguzman something along the lines of your first suggestion makes sense to me:

```ruby
begin
  collection_resource.create(resource: attributes) 
rescue Almodovar::HttpError => exception
  exception.error_messages # => ['Title has already been taken']
end
```

That's fairly similar to what we're doing in some internal BeBanjo components, although we have to parse the response to extract the error messages.

I think we could even use `Almodovar::ValidationErrors` as you're suggesting, as long as we `class ValidationErrors < HttpError`, this shouldn't break any customer code, should it?

**Comment by eliskah** [comment]
Acceptance ✅ 

I would move to release. Just this:

As @littlemove pointed out - do you @cavalle think it would be worth adding this new feature to Almodovar [documentation](https://github.com/bebanjo/almodovar/blob/master/README.rdoc)?

Also, I don't know yet how we manage releasing features in Almodovar. Is there a special process or anything?

**Comment by cavalle** [comment]
+1 to add some notes about this feature to the Almodovar README

**Comment by cavalle** [comment]
I think that should be do it as part of the same PR if possible
