### ISSUE TITLE
Inconsistent Resource respond_to? behavior if XML is not loaded

### ISSUE THREAD

**Issue by justinhoward** [bebanjo/almodovar#41]
Sometimes it is useful to check whether a resource responds to a method before its XML is loaded. In code that does automated endpoint discovery, the resource type is not always known. Using `respond_to?` doesn't work that way though.

``` ruby
title = Almodovar::Resource('http://movida.example.com/api/titles/1234', auth)
titles.respond_to?(:create) # should be false, but returns true
titles.respond_to?(:update) # should be true, but returns false
```

This doesn't work because the first call to `respond_to?` locks the resource to be a `ResourceCollection` and returns true. The second call then fails, because it gets forwarded to the cached `ResourceCollection` instance.

This does work however:

``` ruby
title = Almodovar::Resource('http://movida.example.com/api/titles/1234', auth)
titles.xml #force the `Resource` instance to load xml and check `xml['type'] == 'array'`
titles.respond_to?(:create) # now this returns false
titles.respond_to?(:update) # returns true
```
## Expected Behavior

The `respond_to?` method should return consistent results regardless of whether the XML is loaded. Or what methods were called previously.
## Possible Solution

``` ruby
title = Almodovar::Resource('http://movida.example.com/api/titles/1234', auth)

# Before the XML is loaded, any methods common to both resource types should return
# without loading XML.
titles.respond_to?(:http) # return true, don't load XML yet

# we can't know this without loading the XML, so check xml['type'] now
# and create a SingleResource object
titles.respond_to?(:create) # return false
titles.respond_to?(:update) # return true
```

For some methods like create and update, we want to be able to call them without loading the XML first:

For create:

``` ruby
titles = Almodovar::Resource('http://movida.example.com/api/titles', auth)

# First perform the POST, then if it succeeds, set the resource class to ResourceCollection.
titles.create(name: 'Foobar')

# we called create successfully, so this will get forwarded to the new
# ResourceCollection instance without the need to load the XML
titles.respond_to?(:create) # return true
titles.respond_to?(:update) # return false
```

And for update:

``` ruby
title = Almodovar::Resource('http://movida.example.com/api/title/1234', auth)

# First perform the PUT, then if it succeeds, set the resource class to SingleResource.
titles.update(name: 'Foobar')

# we called update successfully, so this will get forwarded to the new
# SingleResource instance without the need to load the XML
titles.respond_to?(:update) # return true
titles.respond_to?(:create) # return false
```

There is one downside to this approach. It will introduce a slight inconsistency if you call a method that an endpoint does not support. I don't think it's possible to fix this while keeping the lazy loading behavior:

``` ruby
title = Almodovar::Resource('http://movida.example.com/api/title/1234', auth)

# Here we're trying to call create on an non-collection endpoint. So this method call
# will succeed, but throw an error
begin
  title.create(name: 'Foobar')
rescue Almodovar::HttpError
end

# Then afterward if we check responds_to?(:create), it will return false
# even though we were able to call it above
title.respond_to?(:create) # Loads XML, checks xml['type'] and returns false

# Now, since we've created a ResourceCollection instance,
# the create call will fail.
title.create(name: 'Foobar') # NoMethodError
```
## Workaround

Right now, to get around this problem, I'm checking `xml['type']` manually to see if a resource is a collection. If it's too involved to fix the `respond_to?` behavior, one option would just be to introduce a `collection?` method that would formalize the `xml['type'] == 'array'` check.

**Comment by maxcosworth** [comment]
Thanks for reporting this, @justinhoward.

You're right, this is not consistent, and it should be. It's a bit tricky to make it work right, tho, but let me give it a try in the coming days...

**Comment by justinhoward** [comment]
I no longer use Bebanjo products for my work, and this is abandoned, so I'm closing.
