### ISSUE TITLE
Deprecation warning with ActiveSupport 5

### ISSUE THREAD

**Issue by justinhoward** [bebanjo/almodovar#46]
Since ActiveSupport 5, `alias_method_chain` is deprecated. When loading Almodovar, the message

> DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from require at /home/justin/projects/movida-events/lib/movida_events.rb:7)

is displayed twice.
## Possible Solutions
1. Add "< 5" to the gem dependency.
2. Use `Module#prepend` instead of `alias_method_chain`. This requires Ruby >= 2.0.

**Comment by maxcosworth** [comment]
Thanks, @justinhoward. Yep, we should definitely adopt `prepend` instead of `alias_method_chain`.

**Comment by AlfonsoUceda** [comment]
@justinhoward this issue because Almodovar was bumped to version 1.7.0 and `alias_method_chain` was removed. Thanks for the issue :)
