### ISSUE TITLE
Rewrite Almodovar

### ISSUE THREAD

**Issue by AlfonsoUceda** [bebanjo/almodovar#48]
Almodovar was done with a lot of dark meta-programming, it's very difficult use it in tests and sometimes can give unexpected results in production code.

We should have every entity of Movida and Sequence in Almodovar (or create another gem for easy an migration).

An inspiration can be https://github.com/octokit/octokit.rb or other gem to access some API.

cc @bebanjo/devs

**Comment by demimismo** [comment]
Casiná! I agree, but this is not going to be easy 😄

**Comment by AlfonsoUceda** [comment]
yeah, I was just talking with @dsaenztagarro and I decided to open the issue, just to know that in some moment of the future we should take care of this hehehe.

**Comment by pacoguzman** [comment]
I have to say that I like it once you know what you can do is super issue to use with our apps and does not need syncing with changed on our APIs

**Comment by maxcosworth** [comment]
@AlfonsoUceda, could you provide a bit more context on the motivation to open this issue? So that we can understand the problem/need better.

I've not used it much, that's true, but I don't see a problem in how it works either. I mean, it's flexible and kinda reliable, isn't it?

**Comment by AlfonsoUceda** [comment]
My motivation to open this issue was a discussion with @dsaenztagarro at the office, he has been using Bond more than me, I used it more when I was in projects team I have to say.

One of the problems of using Bond in tests is difficult to use, you can't mock it in an easy way, you have to use webmock to capture the request and avoid make external requests, @dsaenztagarro can expand this issue.

Almodovar makes a request when `#inspect` method is called and this is done with metaprogramming, do you think this is a good behaviour? sometimes I had problems with this behaviour using Almodovar, It was a little bite more difficult use it because of this black magic.

One point of favour is that you don't need change Almodovar when there is a change, but I prefer see the API in Almodovar instead in the API itself. A lot of gems that wraps APIs use this style, you can navigate through code and see every object with their methods, making easier the gem readability and testability.

### Summarizing
- Advantages:
  - You don't have to create a new version when you modify the API
- Disadvantages:
  - Readability
  - "Testabilty"
  - Bad user experience, this is because I explained before related to `#inspect` method.
  - Maintainable

**Comment by pacoguzman** [comment]
Thanks @AlfonsoUceda but IMHO you're not correct with `Readability` and `Maintainable` at least as a client library.

Do you know what happen when you don't test you're HTTP client correctly that a lot of bug raise when executing in a production environment. I feel more confident testing with webmock than using some POROs objects to simulate responses like we started doing with Bond handlers for a specific company, later all the Bond handlers are tested using WebMock and I don't think we had problems with Almodovar and its default behaviour.

**Comment by AlfonsoUceda** [comment]
@pacoguzman I wanted to say `Readability` and `Maintainable` for the source code not as client library.

**Comment by pacoguzman** [comment]
:+1: I think it makes more sense to create another client library than rewrite this, dealing with version can be very difficult and tedious.

**Comment by justinhoward** [comment]
As a developer for Machinima, a Movida customer, here's my 2 cents. I don't see any need for a rewrite or a new client. I found almodovar's approach to be simple and discoverable. The Movida API documentation is good and reading it is mostly enough to learn how to use almodovar. You say that PORO wrappers would help with readability and user experience, but I have usually found the opposite. Heavy-weight wrappers around an API usually only serve to _obscure_ the API and add an unnecessary abstraction layer. For simple use-cases, this is sometimes easier, but when using the API heavily, it typically just gets in the way.

Also, please consider that you have clients (including Machinima) who have invested many hours of development time into almodovar. Abandoning it isn't really an option from my perspective.

**Comment by cavalle** [comment]
@justinhoward thanks for your input, it's really valuable to us. I'm very glad you find Almodovar and our APIs easy to use, we definitely tried to make them that way.

I agree abandoning isn't really an option, so rest assured that we'll keep maintaining Almodovar as you know it. 

That said, I think there are some valid concerns discussed in this thread, things in Almodovar that we may want to improve in the gem, particularly in its internals, without breaking its API.

**Comment by AlfonsoUceda** [comment]
Folks, thanks for the discussion but for now I'm going to close this issue ;)
